### ISSUE TITLE
Stabilire guidelines per la nomina dei nuovi ambassador

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#1]
Apro questa issue per raccogliere commenti e idee sulle nuove guidelines.

Ci siamo detti che a fine settembre chiuderemo le nomine per gli ambassador, ma è corretto che nelle prossime settimane vengano stabilite delle guidelines per le prossime nomine.

Non ho ancora un'idea su come gestire le votazioni negative, ma ecco la mia idea sulle nomine:
- Attorno a metà mese si andrà ad aprire un sondaggio su Telegram riguardo al numero di nuovi ingressi nel team, aperto fino all'ultimo giorno del mese
- I primi giorni del mese successivo verranno nominati, in ordine di voti, le X persone stabilite nel sondaggio.

Chiaramente il sondaggio potrebbe anche identificare un numero pari a 0.

**Comment by JeyDi** [comment]
Ciao @Cadienvan attualmente le regole che abbiamo stabilito sono:
- almeno 2 voti per ogni ambassador
- votazioni positive > a quelle negative
- in caso di tante votazioni negative sentire la persona in privato per capire come procedere

Possiamo scrivere queste regole da qualche parte?

Manca secondo me la decisione di quando aprire questi periodi di nomina dei nuovi ambassador e io metterei anche una valutazione degli attuali basata sulla contribuzione, in modo che possiamo avere all'interno degli ambassador le persone che collaborano davvero al progetto.

**Comment by Cadienvan** [comment]
Sono d'accordo per questo ho lasciato aperta la discussione.

**Comment by Cadienvan** [comment]
Aspetterei a scriverle le regole una volta che le abbiamo confermate per il "2.0" post chiusura

**Comment by BrianAtzori** [comment]
Un dubbio su questa cosa: gli ambassador possono essere "infiniti"? Cioè l'idea è includerli periodicamente, ma con un tetto temporale oppure con un tetto in numeri? 

Lo chiedo perchè soprattutto finchè non si rifinisce l'onboarding (giustamente) sono persone che dovranno essere seguite, ascoltate ecc ecc, non so se mi sono spiegato, non voglio stabilire un governo oligarchico 😂

**Comment by Cadienvan** [comment]
@BrianAtzori https://github.com/Il-Libro-Open-Source/governance/blob/main/meetings/2023-10-04-Governance.md qui puoi trovare i punti di giornata di qualche giorno da del Governance Meeting, tra questi c'è la stesura di un tentativo di linee guida :)

**Comment by Cadienvan** [comment]
Chiudo perché collegata a #23 #25 e #29
