### ISSUE TITLE
Punti in attesa del primo Communicatios Group Meeting

### ISSUE THREAD

**Issue by imD3v** [Il-Libro-Open-Source/governance#10]
In attesa di definire la prima data utile per effettuare la prima riunione ufficiale del neo nato Communications Group, condivido alcuni punti che potrebbero servire per identificare ODG della riunione.

- Netiquette di chat tra ambassador (servono, non servono? anche in vista dei nuovi arrivi)
- Bot telgram di gestione gruppo? (utile?)
- Definizione dei sondaggi ( Quanto tempo minimo prima della scelta, dove e come comunicarli, regola di approvazione (esempio : impostiamo un quorum? - Forse è più governance questo? )
- Definizione delle comunicazioni in merito agli incontri dei singoli gruppi ( che sono comunque aperti a tutti ) e global ambassador.

Come già risposto su Telegram da @Cadienvan il punto 3 (proposto in precedenza sulla chat) verrà fatto partire da Governance e poi stabilito da tutti.

@sensorario 
@elgorditosalsero

**Comment by Cadienvan** [comment]
Butto lì un'idea..
Che ne pensate di touchpoint magari una volta ogni 2/3 settimane? Cioè solo un meet in cui chi vuole entra e parla di ciò che sta facendo. Ovviamente scrivo qui perché lo intendo esteso a tutti gli Ambassador, magari aperti anche alla community!

**Comment by Cadienvan** [comment]
@imD3v si può chiudere questa?
