### ISSUE TITLE
Gestione Canali Social per comunicazione Libro Open Source

### ISSUE THREAD

**Issue by halfpass25** [Il-Libro-Open-Source/governance#17]
Sempre quel rompiscatole di Pasquale, scusate!

Probabilmente avete già letto tutti le questioni che ho sollevato in merito, approfittando dell'ormai prossimo
evento CodeMotion che certamente è un'ottima vetrina per il progetto del Libro Open Source.
E ho capito che tra la fretta di mettere su le cose, il titolo definitivo che ancora non c'è ed altro, per il CodeMotion
ci arrangeremo, cercando comunque di stabilire condotte e Tone Of VOice per quello che pubblicheremo dai nostri
accounts social individuali.

In prospettiva, però, mi pareva giusto pensare a qualcosa di più strutturato e gestito.
Non dubito che qualcun altro ci abbia pensato al pari mio, però non ho letto molto in proposito e quindi, anche qui,
lancio proposte/domande, eventualmente da risolvere via sondaggi, vedete voi.

1) su quali canali vogliamo essere presenti? LinkedIn è assodato con una "pagina" e va bene ma per il resto?
Non è certo il caso di disperdersi in mille canali e rivoli e quindi immagino che i canali più appropriati  possano essere quelli
in qualche modo più "tecnici" (Slack, Discord, dite voi...).
Non so cosa pensiate di FB ma non mi sembra luogo idoneo, poi per carità, opinione personale.

2) Un account Instagram può servire seriamente, per una migliore, più capillare e diversificata comunicazione?

3) E' il caso di pensare anche ad una eventuale "NewsLetter" sempre su LinkedIn?

4) avete altri canali che non ho citato da prendere seriamente in considerazione?

5) E' pacifico che anche per la gestione Social, avremo delle regole che al momento è inutile ipotizzare, ne parliamo a canali selezionati.

A parte ciò, visto che mi occupo solo di traduzioni e non voglio lasciare a nessuno pesi in più, faccio presente di avere trascorsi
sufficientemente lunghi e qualificati anche da Social Media Manager e dunque, se lo ritenete, posso occuparmi o della gestione degli eventuali canali social che apriremo o comunque di fare da collettore per i contenuti da pubblicare.

E chest'è, fatemi sapere e buona giornata! ;)

**Comment by Cadienvan** [comment]
Grazie Pasquale, 
tutti ottimi spunti, l'idea generale era quella di veicolare il tutto su LinkedIn essendo il social più attinente, ma possiamo valutarlo ovviamente!

Riguardo alla Newsletter credo sia uno spunto di discussione interessante, parliamone, ma dubito che ora ci sia sufficiente materiale.

**Comment by halfpass25** [comment]
Certo, erano solo possibili scenari allo scopo di dare massima diffusione (ad-hoc) del progetto.
Se ci sono idee e proposte più idonee o che ho dimenticato, tanto meglio 👌

**Comment by guizzo** [comment]
Io, dall'alto della mia ignoranza in campo social, penso che per il momento sia il caso di concentrarci su un unico canale social, ossia LinkedIn.

Il timore è quello di ritrovarsi a dover gestire più cose di quelle che effettivamente riusciamo a gestire.

Fermo restando che in futuro nulla ci vieta di allargarci anche ad altri social/canali di comunicazione, per quello penso si faccia sempre in tempo.

**Comment by GuidoPenta** [comment]
Sono d'accordo con @guizzo , al momento dato che siamo in fase iniziale mi concentrerei su linkedin, che comunque ha già sufficiente "potenza di fuoco" mediatica a mio avviso :)

**Comment by corradopetrelli** [comment]
Condivido il pensiero di tutti, rimaniamo per ora sul semplice 😄

**Comment by BrianAtzori** [comment]
Ciao ragazzi, avevo da tempo immemore questa issue nei to-do perchè mi interessava partecipare!
Ho studiato un pochetto marketing e sto seguendo occasionalmente un master anche in questo ambito e credo che possa essere utile il mio contributo in merito avendo già avuto modo di gestire dei canali social, sono d'accordo con voi che al momento può bastare LinkedIn ma nel dubbio se non è un problema mi assegno la issue per il futuro e per rimanere in gioco su questa cosa, è ok per voi? 🤓

**Comment by Cadienvan** [comment]
@BrianAtzori for sure, appena confermiamo la modalità di accesso ai WG potresti proporti per il Relations! Why not?

**Comment by Cadienvan** [comment]
Il governance group nella riunione del 3 Novembre ha concluso la discussione sull'adozione di ulteriori canali social, confermando per ora l'utilizzo di LinkedIn e Github per le comunicazioni esterne, e Telegram per gli Ambassador. Si è deciso di valutare l'apertura di nuovi canali tra sei mesi, con la responsabilità della decisione affidata al Relations Group.

**Comment by BrianAtzori** [comment]
> @BrianAtzori for sure, appena confermiamo la modalità di accesso ai WG potresti proporti per il Relations! Why not?

È una buona idea! Un altro passo fuori dalla comfort zone 😨
Ho letto anche il resoconto del Governance e ok per i canali social attuali, era giusto per non auto-escludermi da un ambito dove potevo contribuire che mi sono infilato nella conversazione! 
Appena stabiliamo come entrare nei WG darò seguito alla cosa 💪🏻
