### ISSUE TITLE
Stabilire guidelines per l'allontanamento di un Ambassador

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#2]
_Non succede, ma se succede..._

Apro questa issue per discutere con tutti riguardo a come gestire eventuali casi in cui un Ambassador, per qualche motivo, debba essere allontanato dal ruolo. Che sia per non partecipazione o per comportamenti ritenuti non corretti, è giusto avere delle guidelines.

Ecco la mia idea, anche qui parliamone:
Quando si ha la volontà di esprimere un dissenso sarà sufficiente contattarmi privatamente esprimendo il dissenso e giustificandolo.
Da quel momento partirà un periodo di "osservazione" nel quale terrò conto di eventuali altre segnalazioni per la stessa persona.

Una volta raggiunto un numero X di segnalazioni, qualcosa è da fare, ma ancora non ho idea di cosa e di come affrontare la situazione.

**Comment by JeyDi** [comment]
Ciao @Cadienvan abbiamo già inserito questi aspetti all'interno del [Code of conduct](https://github.com/Il-Libro-Open-Source/book/blob/main/CODE_OF_CONDUCT.md).

Pensi che siano sufficienti o sia necessario altro?

A seguito delle ultime discussioni sarebbe bello che ci fossero altri a partecipare a questa discussione.

**Comment by Cadienvan** [comment]
Sì ci manca solo l'aspetto più "lato", ovvero il caso limite di un Ambassador che, non so, per un anno non contribuisce al progetto nemmeno con un commento. Non fa nulla di male ma è giusto parlare della possibilità di allontanarlo qualora accada.

**Comment by imD3v** [comment]
Ciao ragazzi, 
Secondo me la primissima cosa da fare è capire se bisogna implementare qualcosa qui : [AMBASSADORS.md ](https://github.com/Il-Libro-Open-Source/book/blob/main/AMBASSADORS.md ) (in particolare il punto 4)
Definito definitivamente cos'è un ambassador si possone definire le "motivazioni di esclusione" che possono essere per violazione del [Code of conduct](https://github.com/Il-Libro-Open-Source/book/blob/main/CODE_OF_CONDUCT.md) della mancata partecipazione pro-attiva (qui da capire se in soli termini di scrittura del capitolo, nel senso se non scrivo nulla ma partecipo attivamente alla community sono oppure no un'ambassador? (per me si)  ) , altro?
Sul come invece propongo che come la nomina di ambassador è stata  "votata" dalla community io farei una sorta di genere anche per l'allontanamento, ma in questo caso circoscritto tra gli ambassador ( gli esterni nel concreto non possono sapere il reale impegno di qualcuno )  Si chiede quindi a governace o a communication di creare un sondaggio, segnalando la persona e specificando la motivazione della segnalazione. Se il sondaggio ( in base alle regole di votazione ) risulta a favore della proposta di allontanamento, la specifica persona segnalata riceve uno strike, a 3 sei fuori. 
E' un'idea ma a me sembra abbastanza democratica.

Ps. Spero sia chiaro, sto scrivendo ad occhi semi chiusi dal sonno =/

**Comment by BrianAtzori** [comment]
Aggiungo la mia per confermare che secondo me ciò che ha proposto @imD3v ci sta! 

Una bella votazione tra tutti gli ambassador fa il suo secondo me, in questo modo hai la persona imparziale che magari non ha collaborato direttamente e allo stesso tempo hai anche chi magari ci ha lavorato direttamente alla stesura di un capitolo, ad un'automazione ecc ecc.

Inoltre secondo me con la concretizzazione progressiva del progetto, sarà sempre più chiaro cosa sarà un ambassador nel modo più capillare possibile (magari con una bella infografica che mostra di cosa si occupa) e sarà possibile definire un set minimo di azioni che ti rendono un ambassador, effettuate in un limite tempo.

Io credo sia importante poichè magari una persona come diceva @Cadienvan sta ferma un anno e intanto se ci fosse inclusa un'altra persona, quella risorsa potrebbe essere più efficace nei contributi.

Possiamo anche pensare di creare una sorta di path di richiami, magari gestito da un gruppo di crescita del progetto, niente contributi per 3 mesi (esempio), poi 6 e poi un anno, una cosa del genere... per richiamo intendo ti parlo in un 1v1 per cercare spiegazioni e se è emerge qualcosa del tipo "non so come contribuire" magari cercare di fornire un aiuto.

**Comment by Cadienvan** [comment]
Ottima l'idea del "gruppo di richiamo", potrebbe starci.

Me lo tengo in testa nei compiti di giornata!

**Comment by Cadienvan** [comment]
@imD3v ho proposto qui le mie linee guida: #25 .

Non ho previsto i "3 strike" pur piacendomi l'idea perché se un ambassador viene votato dalla maggioranza e poi rimanesse credo che per nessuno sarebbe piacevole. Chi l'ha votato sarebbe di malumore, il soggetto si sentirebbe alle corde e in generale non ci sarebbe un bel mood.

Credo più nel "al primo strike sei fuori, ma se ci convinci rientri con una bella pacca sulla spalla"

**Comment by BrianAtzori** [comment]
Si forse hai ragione, diciamo che in generale già arrivare a una votazione di questo tipo credo implichi che in parte il mood si è già guastato o è a rischio guasto, prolungare i tempi potrebbe essere rischioso, con rilanci e strike intendo quindi approvo la scelta 👍

**Comment by Cadienvan** [comment]
Chiudo perché collegata a #23 #25 e #29.
@BrianAtzori @imD3v @JeyDi nel caso riportate eventuali altri commenti lì dentro

**Comment by halfpass25** [comment]
L'allontanamento per totale assenza di contribuzione, anche solo proposte o commenti costruttivi mi sembra un buon motivo per la rimozione dall'incarico/ruolo.
A prescindere dalle ragioni dell'assenza, che potrebbero anche essere giustificate e giustificabili, una persona che non può/non vuole/non sa produrre un minimo di qualcosa, è bene si faccia da parte, magari lasciando il ruolo a new entries 👌
