### ISSUE TITLE
Nascita del ruolo Consulente/Amico

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#23]
Dal Governance Meeting di qualche giorno fa è nata la possibilità di identificare un nuovo ruolo simil-Ambassador per tutti coloro che hanno la possibilità di contribuire al progetto, ma non in maniera attiva con la stesura dei contenuti.

La mia proposta è quella di creare una figura di _Consulente_, o _Amico_, quindi una figura che è familiare al progetto e ne appoggia principi e obiettivi, ma senza la pressione della stesura dei contenuti.

Questo ci permetterebbe di abbassare il numero di Ambassador ma allo stesso tempo non perdere figure valide che verosimilmente non hanno il tempo di stendere interi argomenti.

Pensavo alle seguenti linee guida:
- Fino a che non ne verranno proposte di differenti, le nomine seguiranno le stesse regole degli Ambassador.
- A livello di org, avranno il ruolo di _Triage_, così da poter essere taggati nelle review ma non poter scrivere direttamente sul repo, creando una separazione di responsabilità rispetto agli Ambassador.
- Una figura _Amico_ non avrà vincoli di reviewing ma si stabilisce un tetto minimo di 3 review al repository **book** nell'arco di un anno solare. Eccezioni verranno fatte qualora le review siano inferiori ma di più alto valore, o la scrittura di contenuti impattanti.
- Una alternativa a quanto sopra è la sponsorizzazione o il supporto in altra forma al progetto. In questo caso sarà il _Relations Group_ a stabilire se l'impatto sulla community e sul progetto della persona in essere, a fine anno, sia ritenuta sufficiente a mantenere il proprio ruolo.

Chiaramente quanto sopra può essere splittato in due ruoli ben specifici di consulenza e supporto.

**Comment by corradopetrelli** [comment]
Due cose:
- Direi di non usare il termine Amico ma di usare qualcosa di più inclusivo. Che ne dici di Support o Friend? 
- Direi di non mettere un tetto alle review della figura _Amico_ perchè è difficile da tracciare. In aggiunta dato che mi immagino che siano gli Ambassador a mettere in review la figura Amico su una determinata PR sarà responsabilità degli assegnatori di non sovraccaricare l'assegnato

**Comment by eppak** [comment]
Io ho un argomento che vorrei affrontare ma causa impegni e bisogno di rielaborazione sto spostando in avanti dando una mano su altro. Questo intendo dovrà mettere un tetto temporale a questa intenzione, si ha già un orizzonte?

**Comment by Cadienvan** [comment]
@corradopetrelli sì, il termine è provvisorio e serve giusto a dare un'idea.
Pensavo al paletto minimo di 3 proprio perché non vorrei che siano gli ambassador a chiedere la review, ma siano proprio queste figure in autonomia a fare queste review.

@eppak direi democraticamente 14 giorni saranno più che sufficienti, tempo di dare a ognuno il tempo di elaborare alternative. Il concetto è quello di avere _qualcosa_ piuttosto che non avere nulla e da lì rielaborare.

**Comment by imD3v** [comment]
@Cadienvan io sono scettico in merito a questa posizione e cerco di motivare la risposta.

Consideriamo per esempio valida la issue di @EMCestari sulla definizione di Ambassador (che condivido al 100%) come prima cosa ci troviamo in una situazione interna attuale già potenzialmente critica da gestire. 

Con la più totale serenità e trasparenza mi domando: tutti gli attuali Ambassador in carica rispettano almeno 1 dei 3 punti descritti nella issues in questione? 

Se la risposta è negativa che fine faranno questi attuali Ambassador? Diventano Friend? Li facciamo uscire? È potenzialmente brutta come cosa.

Che differenza c'è tra un Friend e un contributor X che vuole partecipare in modo sporadico? A questo punto tutti coloro che contribuiscono anche un minimo al progetto con una PR sono friend o sbaglio? Quindi serve davvero questa figura?

Poi se invece quello che stiamo cercando di definire è più orientato verso lo "sponsor" ossia qualcuno che si può anche (come non) occupare dei contenuti ma si prende la briga di rappresentare il progetto "nel mondo" allora potremmo aggiungere un punto 4 alla issue di @EMCestari e mantenerlo Ambassador no?

Non so se mi sono spiegato a meglio.

**Comment by Cadienvan** [comment]
@imD3v condivisibile ciò che dici, sono d'accordo sul fatto che sia un po' una figura "di mezzo", ma l'intento è proprio permettere un'anello di congiunzione tra Ambassador e contributor che magari partecipa, ma lo fa in un modo differente.

L'idea è proprio permettere di "pucciare i piedi" nel progetto a contributor di valore e, allo stesso tempo, di permettere una via di mezzo a chi non ha modo di contribuire ma vuole comunque restare attorno al progetto!

**Comment by imD3v** [comment]
@Cadienvan sisi è abbastanza chiara la posizione però continuo ad avere dei dubbi onestamente.
Anche perché aggiungere un ulteriore etichetta ne consegue anche lì delle regole di ingresso e di uscita.
Come divento "Friend" e come perdo questa nomina? Quali sono effettivamente i miei "doveri"? 
Se non ci sono queste questioni e un Friend non ha "diritti e doveri" in quanto appunto "amico" del progetto  (secondo me) non ha molto valore se non quello "mediatico" 

Se poi è il valore "Mediatico" che stiamo cercando con questa posizione ( è ci può anche stare ) allora ok però ecco non la differenzio molto da qualsiasi altra persona che voglia parlare del progetto su un blog o altro o partecipare con una PR a del contenuto senza avere effettivamente un' etichetta all' interno del progetto.

Comunque di base come per tutto, io mi adeguo felicemente alla maggioranza.

**Comment by Cadienvan** [comment]
Capisco il tuo punto, lo vedi quindi come una "etichetta non necessaria" in quanto se vuoi darci una mano ce la dai altrimenti no, ho capito bene?

**Comment by BrianAtzori** [comment]
Io mi trovo un po' a metà strada tra le opioni, credo che ci possa stare un ruolo a metà tra ambassador e contributor, ma è importante definirne i ruoli e le relative procedure. 
Purtroppo è facile che con queste cose si pestino i piedi a qualcuno ed avere tutto chiaro credo sia importante, allo stesso tempo forse è una cosa da segnare e da lasciare aperta ma magari è una complicazione non necessaria allo stadio attuale, mi rifaccio a ciò che dicevo in un altro thread... forse con la crescita del progetto sarà sempre più chiara e "raffinata" la definizione di Ambassador e di conseguenza, altre figure (se necessarie) seguiranno a ruota

**Comment by guizzo** [comment]
A me questa idea non convince molto, ho gli stessi dubbi di @imD3v...è davvero necessaria un ulteriore etichetta?

Perché se la introduciamo, allora dobbiamo farlo per bene, e quindi deve essere chiaro cosa si deve fare per ottenerla, qual'è/quali sono la/le condizione/i che la fanno perdere, perché dovrei ambire ad essere Amico/Supporter del progetto e cosa questa etichetta mi differenzia dall'essere un "semplice" contributor che porta le sue contribuzioni al progetto come potrebbe fare chiunque.

_Non lo so Rick_, ho paura che andiamo a confondere ulteriormente le idee a chi si avvicina/vorrebbe avvicinarsi al progetto.

P.S.: se non ricordo male, già la semplice distinzione _Contributor/Ambassador_ ha creato un po' di confusione in tal senso...

**Comment by Cadienvan** [comment]
La nascita del ruolo di Contributor attualmente compensa questa necessità.
