### ISSUE TITLE
Punti aperti in attesa del prossimo Communications Group Meeting

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#26]
## Sondaggio per indice di gradimento dei gruppi

Definizione, pubblicazione e invio di un sondaggio che possa raccogliere feedback e sentimento generale nei confronti del comportamento di ogni gruppo. Si pensava, a titolo di ipotesi, di utilizzare la Scala Likert per i seguenti punti:
- Reputo il lavoro svolto dal gruppo X soddisfacente.
- Reputo il perimetro di responsabilità e potere del gruppo X corretto.
- Reputo necessario che il gruppo X rimanga operativo in quanto ha un impatto positivo sul progetto.

Chiaramente parlatene e diteci come la vedete, il @Il-Libro-Open-Source/governance-group attualmente non ha intenzione di usare i dati raccolti dal sondaggio per prendere decisioni ma solo per poter parlare apertamente di eventuali negatività che possano risultarne.

## Onboarding nuovi ambassador

Pur avendo già portato a termine un quick onboarding è corretto sia stabilito un secondo momento di formazione e benvenuto per i nuovi arrivati.

## Proposta Ambassador meeting

Avevamo tenuto aperta la possibilità di avere dei meeting di riunione e Q&A sparsi per il mese a cui chiunque in libertà potesse partecipare, ma non vedo citata la cosa nelle note che sono state pubblicate, quindi la ripropongo. La mia idea era di individuare un paio di orari e 2-3 giorni e, nell'arco del mese, sfruttando anche il calendario appena creato, aprire questi canali in cui chi vuole può entrare e discutere. Non c'è obbligo di partecipazione né ci saranno delle note di giornata, ma solo momento aperto di discussione e risoluzione dubbi.

**Comment by Cadienvan** [comment]
@Il-Libro-Open-Source/communication-group I primi due punti possono anche essere ignorati, ma il meeting regolare credo possa essere interessante, come la vedete?

**Comment by JeyDi** [comment]
Ciao @Cadienvan c'è ancora l'idea di fare un meeting regolare ambassador? Secondo me è importante farlo nel nuovo anno anche vista la pubblicazione della prima versione de libro (ps: sono tornato! 👯 )

**Comment by Cadienvan** [comment]
@JeyDi so che i ragazzi ne avevano parlato e usciranno delle survey a riguardo!! Giusto @imD3v ?

**Comment by imD3v** [comment]
Yes! @JeyDi  facciamo uscire tutto in giornata.
