### ISSUE TITLE
Approvazione e disapprovazione contenuti

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#27]
Avendo creato i gruppi, come il drafting, che si occupano direttamente dei contenuti del libro, nasce la necessità di stabilire de facto le linee guida di approvazione dei contenuti.

Non creo una PR ma apro una issue perché le linee guida effettive dovranno essere inserite nel repo **book** oltre che prevedere, se necessario, automatismi da parte del @Il-Libro-Open-Source/tech-group .

Segue la mia proposta, che tiene in considerazione la scelta del Tech Group di non utilizzare la funzionalità dei CODEOWNER, per cui la feature non verrà citata.

---

Per l'approvazione di un contenuto all'interno di un branch, che sia da parte di un Ambassador che di una figura esterna, sarà sufficiente:
- Approvazione di almeno il 50%+1 degli Ambassador assegnatari. In caso di non raggiungimento del quorum entro 7 giorni dall'apertura della PR, un qualsiasi altro Ambassador potrà fare le veci degli assegnatari non votanti.
- Superato il tempo massimo di 15 giorni dall'apertura della PR - O 15 giorni dall'ultimo commento da parte di un Ambassador -, questa sarà considerata non valida e verrà chiusa da qualsiasi Ambassador vorrà farlo e verrà richiesto alla persona che ha aperto la PR di riproporla cercando di creare più coinvolgimento o di modificarne il wording.

N.B. Non ritengo necessaria la presenza del Drafting Group in questa fase in quanto sarà comunque necessario un successivo passaggio prima del passaggio a _main_ nel quale loro saranno coinvolti e questo creerebbe solo eccessivo lavoro per il gruppo.

Per l'approvazione di un contenuto all'interno di _main_, che sia da parte di un Ambassador che di una figura esterna, sarà sufficiente:
- Approvazione di almeno 5 Ambassador.
- Approvazione di almeno 1 membro del Drafting Group.
- Superato il tempo massimo di 15 giorni dall'apertura della PR - O 15 giorni dall'ultimo commento da parte di un Ambassador -, questa sarà considerata non valida e verrà chiusa da qualsiasi Ambassador vorrà farlo e verrà richiesto alla persona che ha aperto la PR di riproporla cercando di creare più coinvolgimento o di modificarne il wording.
- Aggiungo una nota: Attualmente è in corso la stesura di una proposta di fondazione di un Content Group che validi l'accuratezza e il diritto d'autore dei contenuti proposti, è plausibile pensare che una figura di questo gruppo debba essere coinvolta in entrambi i processi.

---

Aggiungo a quanto sopra che per la disapprovazione dei contenuti sarà sufficiente che un membro del team Ambassador commenti la PR indicando la sua disapprovazione (Pollice giù 👎, commento chiaro es. "Non approvo questo contenuto"). La disapprovazione andrà a ridurre di _1_ i numeri per il raggiungimento dei criteri di cui sopra. Di conseguenza, a titolo di esempio, una PR verso _main_ con 5 voti a favore e approvazione del drafting group MA con una disapprovazione renderà necessaria un'ulteriore approvazione per poter passare. Lo stesso vale per il conteggio del Drafting Group, per cui la disapprovazione da parte di uno dei suoi membri richiederà l'approvazione di altri 2 di essi.

**Comment by corradopetrelli** [comment]
> un qualsiasi altro Ambassador potrà fare le veci degli assegnatari non votanti

Aggiungerei il fatto che l'Ambassador assegnatario che non ha votato deve mettere come review colui che ne fa le veci. Altrimenti qualunque potrebbe fare le veci di qualcuno che non ha votato.

> Superato il tempo massimo di 30 giorni dall'apertura della PR

Direi "PR aperta". Perchè potrei anche lasciare la PR in draft finchè voglio ma non vorrei che il countdown parta da quando la creo ma dal passaggio da draft a ready.

> (Pollice giù 👎, commento chiaro es. "Non approvo questo contenuto")

Chiederei anche la motivazione della disapprovazione da ognuno.

**Comment by Cadienvan** [comment]
> Aggiungerei il fatto che l'Ambassador assegnatario che non ha votato deve mettere come review colui che ne fa le veci. Altrimenti qualunque potrebbe fare le veci di qualcuno che non ha votato.
Beh ma se non vota è perché non è attivo in quel momento per quello intendevo che superato il tempo limite chiunque degli Ambassador può farne le veci.
> Direi "PR aperta". Perchè potrei anche lasciare la PR in draft finchè voglio ma non vorrei che il countdown parta da quando la creo ma dal passaggio da draft a ready.
Sì ha senso, l'avevo sottinteso ma ha senso.
> Chiederei anche la motivazione della disapprovazione da ognuno.
Sìsì certo, però diciamo che prima di tutto renderei chiaro il fatto che il mio sia un "no".

**Comment by EMCestari** [comment]
Mi trovo d'accordo con tutto, anche io metterei obbligatorio il why della disapprovazione.

**Comment by Cadienvan** [comment]
@EMCestari sì ha senso, l'avevo sottinteso ma nelle linee guida sarebbe esplicito.
