### ISSUE TITLE
Working Group - Come gestire accesso ed uscita

### ISSUE THREAD

**Issue by EMCestari** [Il-Libro-Open-Source/governance#30]
Uno dei temi su cui ci siamo confrontati è il movimento delle Persone nei Working Group.

Andando avanti col progetto, potrebbero accadere diverse situazioni per cui un Working Group debba riorganizzarsi. Per esempio una persona potrebbe accorgersi di non avere più tempo da dedicare e decidere di abbandonare il gruppo, oppure il gruppo potrebbe rendersi conto di avere bisogno di più capacity.

Al momento abbiamo pensato a questa _proposta_ di guideline:

- Ogni Working Group deve definire un numero massimo di persone. Non ha senso avere troppe persone all'interno dello stesso gruppo.
- È responsabilità del Working Group comunicare che ci sono posizioni aperte. Idealmente potremmo rendere lo status di capacity dei gruppi sempre visibile qui su GitHub.
- Chiunque voglia far parte di un gruppo _che abbia posizioni aperte_ è libero di candidarsi. Ovviamente è inutile candidarsi se il gruppo è già al completo, in quanto ciò comporterebbe il rifiuto automatico.
- A fronte di una candidatura, sarà sempre il gruppo a decidere internamente (ad esempio tramite sondaggio o meeting ad hoc) se accettare o no l'ingresso della persona candidata.
- Un'eventuale rimozione di un membro di un Working Group deve essere decisa internamente al gruppo stesso e condivisa in modo unanime dal gruppo.

**Comment by Cadienvan** [comment]
Mi torna tutto.

**Comment by BrianAtzori** [comment]
Anche a me fila tutto, ho solo un paio di dubbi: 
- Per "chiunque voglia far parte del gruppo" e "È responsabilità del Working Group comunicare che ci sono posizioni aperte" intendiamo pescare sempre tra gli ambassador, corretto? Io credo di si, ma nel dubbio chiedo
- Per la candidatura per "gruppo" intendi la singla unit o il gruppo totale di ambassador?

A prescindere dal dubbio secondo me ci sta come procedura!

**Comment by halfpass25** [comment]
Qualcuno prepari un badge "Solo posti in piedi" 😁
Scherzi a parte, mi sembra un meccanismo che può rallentare le cose ma ammetto di non avere un'alternativa da proporre, perciò va bene così 👌

**Comment by guizzo** [comment]
Torna tutto anche a me, a patto che il numero massimo di persone nel gruppo sia una cosa ragionevole..volendo fare un esempio: `5` lo vedo un numero (quantomeno per ora) sensato, `15` è un rave

**Comment by Cadienvan** [comment]
@BrianAtzori 

> * Per "chiunque voglia far parte del gruppo" e "È responsabilità del Working Group comunicare che ci sono posizioni aperte" intendiamo pescare sempre tra gli ambassador, corretto? Io credo di si, ma nel dubbio chiedo

Sì, certamente, solo tra Ambassador.

> * Per la candidatura per "gruppo" intendi la singla unit o il gruppo totale di ambassador?
> 
> A prescindere dal dubbio secondo me ci sta come procedura!

Intendo il Working Group di riferimento. È giusto che se, esempio, il Funding Group apra due posti, sia il Funding Group stesso a nominare le due persone in quanto se aprono dei posti sanno anche cosa stanno cercando.
