### ISSUE TITLE
Proposta: Regolamento Interno Gruppi

### ISSUE THREAD

**Issue by francescobianco** [Il-Libro-Open-Source/governance#34]
Ho notato che il solo file WG.md quando si comincia a descrivere i compiti di un singolo gruppo potrebbe risultare stretto. Introdurrei l'obbligo che ogni gruppo di lavoro prepari un proprio regolamento interno di gruppo, facendo una PR in una nuova cartella chiamata 'wg'. In questo modo al suo interno avremmo file simili a questi:

- wg/GOVERNANCE_GROUP.md
- wg/COMMUNICATIONS_GROUP.md
- etc..

Propongo anche una struttura generale per questi file, che potrebbero essere organizzati come segue:

```markdown
# Group Name

... (descrizione generale del gruppo)

## Compiti principali

... (elencare i compiti principali e le funzioni all'interno della community o nelle varie codebase)

## Composizione del gruppo

... (descriviere il profilo potenziale di un canditato accettabile nel groupp e quali sono le skill più spendibili)

## Autorità

... (indicare quali sono gli argomenti e attività su cui le decisioni di questo gruppo sono insindacabili)
```

**Comment by BrianAtzori** [comment]
Proposta interessante, secondo me può avere senso

**Comment by Cadienvan** [comment]
Anche secondo me ci sta.
