### ISSUE TITLE
Mettere in evidenta con un Badge il numero degli attuale degi ambassador

### ISSUE THREAD

**Issue by francescobianco** [Il-Libro-Open-Source/governance#38]
Sarebbe carino poter mettere un badge nel README che mostra il numero attuale degli ambassador, considerando che nella mia visione questo dovrebbe essere fissato ad un limite di 50, si potrebbe addirittura creare un un badge "Free Seat" (sedie libere) quando il numerno di A. scende sotto 50 e cosi mostrare quanti posti liberi vi sono.

Credo che la questione degli ambassador si presenti bene ad una vera e propria gamification, quindi ci si potrebbe sbizzarrire

**Comment by Cadienvan** [comment]
L'idea mi piace, vuoi provare a buttare giù qualcosa?
