### ISSUE TITLE
Punti aperti in attesa del prossimo Governance Meeting

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#51]
- Stesura di una qualche forma di roadmap che includa capitoli conclusi, iniziati, assegnati, da assegnare, così da capire come ci si sta muovendo e in che direzione.
- Proposta: Rimuovere il vincolo di ri-approvazione quando si modifica un contenuto. Spesso capita che per una suggestion si debba richiedere nuovamente il voto di 6 persone.

**Comment by Efois** [comment]
Ciao Candievan.
Quando si tiene il prossimo governance meeting?
Ho trovato interessante questo tuo progetto

**Comment by Cadienvan** [comment]
Ciao @Efois ,
Grazie per l'interessamento!

I meeting per working group purtroppo non sono aperti a chi non faccia parte del gruppo in quanto si discute di temi che solitamente sono relativi alla gestione del progetto più che verso la community :)

Se ti va di contribuire ti invito a dare un occhio alle PR aperte [qui](https://github.com/Il-Libro-Open-Source/book) con suggerimenti o proposte di modifica!
