### ISSUE TITLE
Punti in attesa del Governance Group Meeting

### ISSUE THREAD

**Issue by Cadienvan** [Il-Libro-Open-Source/governance#7]
Il gruppo è ancora in formazione, quindi questi punti sono da intendersi come _provvisori_.
- nomina e spostamento degli ambassador
- gestione dei Group: monitorare e raccogliere feedback sull'andamento. Pensavo a dei sondaggi da mandare ogni tot.
- drafting group: dovrebbe occuparsi anche di stabilire l'ordine dei contenuti e quali possono entrare nel libro, oppure è meglio che la scelta sia di un altro team / allargata a tutti?
- Uno dei punti esposto da Tech riguarda la possibilità di riportare a singolo repo l'organizzazione. La scelta era dovuta alla volontà di separare ambassador-only dal resto, ma parliamone.
- Suggerimento dall'esterno: potrebbe servirci un "Content Group" Che faccia fact checking Sui contenuti?
- Come si rigetta una PR?
- I nuovi ambassador dovranno essere "accolti", se ne occupa il governance o il communications? Direi governance per il primo ingresso e poi da lì communications, ma parliamone.
- Come funziona l'approvazione dei contenuti verso main? Ok i codeowners, ma sicuro servirà almeno un membro del drafting e dell'eventuale content group, se ci sarà. Magari dobbiamo aumentare di 1 il limite imposto a 2 dei codeowners a 3 aggiungendo il drafting group?
- Chi si occupa di mantenere aggiornata la lista degli ambassador? Pensavo al team Discussion o al team Communication.

**Comment by Cadienvan** [comment]
Aggiungo un punto rielaborato da un suggerimento di @imD3v : Potrebbe aver senso stabilire dei livelli di "criticità" dei vari sondaggi di modo che venga stabilito un quorum e un tempo prima di chiuderli?

Pensavo a una cosa del tipo:
- Scelta fondamentale e a lunga gittata: 70% sì, 15 gg.
- Scelta fondamentale e rapida: 80% sì, 5gg.
- Scelta di media importanza e a lunga gittata: 50% sì, 15 gg.
- Scelta di media importanza e rapida: 60% sì, 3 gg.

Sono ovviamente esempi buttati a casaccio.

**Comment by imD3v** [comment]
@Cadienvan non saprei, chi decide quale scelta è più importante rispetto ad un' altra?
Per il principio di democraticità stabilirei una data ed un quorum fisso per tutto.

L'approvazione è sulla base della maggioranza dei presenti (in questo caso dei votanti) e se raggiunto il quorum.

**Comment by Cadienvan** [comment]
Potrebbe aver senso, in effetti si rischia di cadere nella trappola della troppa burocrazia.

**Comment by halfpass25** [comment]
"Suggerimento dall'esterno: potrebbe servirci un "Content Group" Che faccia fact checking Sui contenuti?"

I contenuti di chi? È vero che più occhi vedono meglio di due ma non diamo per scontato che i contributi portati individualmente non siano favolette ma fatti presi dalla realtà? Per quanto allettante l'idea, credo che ogni topic e capitolo del libro poggi su dati di fatto e molto meno sulle opinioni.
A chi lo facciamo sto fact- checking, agli ambassador o ai contributors esterni?
Non facciamo prima a dire a questi ultimi -qualora intendessero collaborare-, che il fact-checking è a loro carico, pena una pessima figura con chicchessia?
Non so, dite anche voi come la vedete 👌

**Comment by Cadienvan** [comment]
@halfpass25 forse ho inteso male io il punto.. suggerisci quindi di dare per buono ogni contenuto scritto a prescindere da chi lo scriva? Se ho capito male scusami, ho "baby shark" nelle orecchie da un'ora 🤣

**Comment by halfpass25** [comment]
> @halfpass25 forse ho inteso male io il punto.. suggerisci quindi di dare per buono ogni contenuto scritto a prescindere da chi lo scriva? Se ho capito male scusami, ho "baby shark" nelle orecchie da un'ora 🤣

Figurati, Michael, io nelle orecchie, stasera ho Billie Holiday con Night & Day (che sia un segno?... 😅).
Per risponderti: si, immagino che qui siamo tutti abbastanza seri e maturi da capire che scrivere un "manuale del buon dev" sia un'attività che richiede tanta, tantissima onestà intellettuale, oltre che competenza e se possibile una significativa esperienza tratta dalla vita reale.
Poi per carità, se pensiamo di non poterci/doverci fidare di niente e di nessuno, istituiamolo sto gruppo dedito al fact-checking ma a me sembra una fatica nella fatica (perché questo libro, al di là del piacere di avervi contribuito, alla fine non sarà esattamente una passeggiata di salute, lo sappiamo, no?... 😁💪👌

**Comment by Cadienvan** [comment]
Però come previeni la situazione in cui un contributore, Ambassador o meno, inserisce anche solo un errore grammaticale? O peggio ancora se una figura dall'esterno per un qualsivoglia motivo, anche un semplice bot, si mettesse a fare PR su ogni capitolo inserendo spam? O, ultima ipotesi, una situazione reale per cui qualcuno inserisce un paragrafo che non è corretto ed è basato su una propria supposizione e non su fatti reali..? La persona potrebbe farlo in buona fede ma ciò non toglie che nel libro venga inserito un contenuto forviante.

**Comment by Cadienvan** [comment]
Come ci si propone per un working group?

**Comment by Cadienvan** [comment]
Communication ci chiede se e come stabilire warn sul gruppo telegram ed eventuale ban. Nota personale: lascerei a loro la decisione.

**Comment by Cadienvan** [comment]
Sempre da comm: stabilire quorum di sondaggio e numero di giorni prima della chiusura.
