### ISSUE TITLE
Governance e Processi decisionali, rilevo delle criticità

### ISSUE THREAD

**Issue by francescobianco** [Il-Libro-Open-Source/governance#9]
## Premessa

Premetto che queste valutazioni sono motivate dall'idea di migliorare la qualità complessiva del progetto, mi concedo di estendere la parola progetto non soltanto al libro, ma a tutta la sua communità. La quale ha il compinto di farlo crescere e farlo vivere come opera autonoma e indipendente da ogni condizionamento o da ogni interferenza, come ad esempio appetiti commerciali e di profitto.

La mia visione forse troppo idealista del progetto è quella di una comunità con dei valori che fanno eco ai valori fondanti del software libero. Tali valori, sono oggi riproposti in vari modelli di governance, la mia idea è che in questo progetto sia chiaro sin da subito a quale [modello di governace](https://www.redhat.com/en/blog/understanding-open-source-governance-models) ci si inspira. Non essere passati prima su questa considerazione è già un primo, ma geniuino sintomo, di una community ancora giovane che può commettere passi falsi. Ignorarne però l'importanza di conoscere e riconoscersi dentro dei modelli di governance, protrebbe risultare una colpa. Il semplice aver letto non implica aver colmato il gap. Il passo fondamentale è quello di ricondursi e lasciare traccia della scelta fatta sul proprio manifesto.

Essendo un sostenitore delle politiche di [open government](https://en.wikipedia.org/wiki/Open_government) applicate attraverso l'uso dei processi di peer-review e pull-request. Questo, non per motivi di gusto, ma perchè tali procedure implicano trasparenza, dedizione e cura della propria contribuzione (su questo aggiungo una nota finale). Qui il punto focale, dal mio punto vista ogni decisione ad oggi presa che non sia stata approvada da una pull-request sul progetto 'governance' è fonte di rischi e di contestazioni potenziali (questa è la mia opinione). Inoltre, tentennare ancora oggi, e non impostare sin da subito un robusto processo decisionale basato sulle pull-request nel progetto 'governance' lo considero un forte elemento di rischio della trasparenza e della integrità del progetto.

## Critica al processo decisionale

In altre parole, vorrei che tutti si domandassero qunto segue: "quali sono le misure che sitamo adottando per garantire che questo progetto rimanga fedele ai principi del software libero?". Se la risposta è non saprei, oppure, stiamo democaritmantente decidendo usanto telegram, bene questa risposta protra convincere il 99% della community ma assolutamente non convince me.

Qui non si tratta di: "Non mi piace Telegram". Il mio pensiero è: "I processi decisionali basati su Telegram sono vulnerabili ed espongono la community a ritrovarsi vittima di interferenze non in linea con i principi fondanti".

Ribadisco e sottoscrivo che: "Credo nella buona fede di tutti"

Ma il mio contributo a questo progetto voleva essere proprio quello di dare significato al suo nome "Libro Open Source", per fare questo devo riportare e segnalare tutto cio che ritengo non sia idoneo.

Ribadisco che le mie sono opinioni personali e non verità assolute che possono essere riscontrate in qualche modo.

Vorrei portare come evidenza del fatto che questa sia una grave lacuna, la mancanza di una sezione in questo progetto che descrive i processi decisionali. So che potrebbe essere opportuno rispondere con un semplice "facciamola". E la facciamo pure...

Però, continuare a prendere decisioni senza aver fissato nero su bianco dei processi decisionali, e non usare processi decisionali trasparenti. Mi portano nella critica situazione di non vedere con interesse il progetto.

## La cura della propria contribuzione

Le regole che ci governano meritano cura e perizia, esse non posso essere il frutto di un sondaggio a cui ho risposto mentre ero a godere della mia vita personale. Avere cura del mio "contributo" alle regole fondanti, implica la dedizione massima. Sono convinto che sia giusto accettare solo contributi di chi si è impegnato aggiungendo valore al progetto e non semplicemente avendo riportato una opinione. La differeza tra contributo e opinione potrebbe non risultare chiara, lascio qui la cosa senza mettere esempi, sperando che cogliate da i miei sforzi, le mie idee. Grazie.

## Conclusione

In conclusione, vi chiedo una risposta chiara, limpida e sincera, su quanto esposto. Forse sarà troppo rigido, però se ritenete eccessivo o macchinoso o inutile quanto esposto per favore, riportatelo. Oppure se ritenete importante o interessante la questione, riportatelo pure.

**Comment by corradopetrelli** [comment]
Sono d'accordo con te sul fatto che trovare il giusto equilibrio nella governance di un progetto è fondamentale. Una governance troppo rigida può rallentare il processo decisionale e limitare la creatività, mentre una governance troppo permissiva può portare a una mancanza di coordinazione e responsabilità diffuse.

È positivo che abbiamo identificato degli ambassador e che ci sia qualcuno disposto a prendere maggiori responsabilità all'interno del progetto. Questa è una buona base su cui costruire.

Secondo me il nostro approccio attuale di permettere ai vari gruppi di prendere decisioni in modo distribuito sembra essere un passo nella direzione giusta. Con il tempo e l'esperienza, potrete sviluppare una struttura più solida per gestire il progetto.

Attualmente son stati creati dei team dove il buon @Cadienvan ha egregiamente separato le responsabilità ed secondo me ciò ci permette di:

- Sviluppare una struttura organizzativa chiara. Questo introduce la definizione di ruoli e responsabilità per i membri del team, in modo che tutti sappiano cosa ci si aspetta da loro;

- Lavorare su sistemi di comunicazione efficaci sia all'interno del gruppo che verso l'esterno ci permette di coordinarci al meglio;

- Impegnarci per creare un qualcosa di qualità. Questo contribuirà a mantenere un elevato standard di contenuto grazie al Drafting Group;

- Prevedere procedure per accogliere nuovi membri e per consentire a coloro che desiderano lasciare il progetto di farlo in modo ordinato:

La nostra governance dovrebbe essere flessibile ed adattabile alle esigenze che emergono nel corso del tempo. Non dobbiamo avere paura di apportare modifiche quando necessario.

È positivo che ci troviamo in una fase di "bozza", stiamo cercando di stabilire le nostre fondamenta. Con il tempo potremo creare dei confini più definiti e rafforzare la nostra governance.

A mio parere dobbiamo continuare a lavorare insieme e ad adattarci alle sfide che incontriamo lungo il percorso.

**Comment by guizzo** [comment]
Ho letto tutto quanto scritto da @francescobianco e sono qui per dare il mio contributo/esprimere il mio pensiero.

Avere una governance e delle linee guida ben definite è importante; importante prima di tutto per una buona riuscita del progetto, ma anche per coordinarci al meglio, separare le responsabilità di ogni gruppo e delineare chiaramente dove finisce il campo di azione di uno e inizia quello dell'altro.

Quindi si, sotto questo aspetto mi trovo in linea.

Sono però altresì convinto che, fino ad oggi, ciò che abbiamo fatto e stiamo facendo ha dell'incredibile. 

Ci siamo riusciti "per fortuna"? Non credo. 

È una casualità? Nemmeno.

La verità, dal mio personalissimo punto di vista è che, chi più e chi meno (complici sicuramente i vari impegni), siamo tutti fortemente motivati e crediamo in questo progetto e nelle sue potenzialità, ma soprattutto abbiamo dimostrato e stiamo dimostrando di avere pragmatismo ed essere in grado di adattarci ed evolverci assieme al progetto stesso e alle difficoltà che di volta in volta ci si parano davanti.

È una governance perfetta? Assolutamente no, molto lontano dall'esserla.

Sta funzionando? Si, finora si.

Detto ciò, concordo solo parzialmente con @francescobianco: magari non nell'immediato, ma una governance più chiara potrebbe essere di aiuto più in là, soprattutto immaginando un futuro in cui non avremo _soltanto_ 200 stelline sul repo e un manipolo ristretto di contributori.

Quello che, a mio avviso, deve  essere chiaro e che ci tengo a marcare è quanto segue:
**Evitiamo come la peste di over-strutturare dove non strettamente necessario, perché da lì a diventare un monolite lento ed ingombrante, secondo me, il passo è davvero breve.**

**Comment by imD3v** [comment]
Spesso la verità si trova nel mezzo! 

Condivido al 100% pensiero estratto da @guizzo e di conseguenza parte del pensiero di @francescobianco.

Adattiamoci nel modo più smart a quello che potrebbe essere in questa prima fase il giusto compromesso.

@francescobianco cosa si potrebbe fare a stretto giro e con un basso impatto operativo per poter intraprendere una strada più solida secondo il tuo punto vista?  

Abbiamo discusso e fatto sondaggi per capire come gestire al meglio il repo, credo che possiamo ( dobbiamo ) intervenire insieme anche su questo giustissimo punto.

**Comment by eppak** [comment]
Ho sempre trovato complicato bilanciare l'entusiasmo e la disciplina nella partenza di un progetto, è un'arte difficile e trovo interessante il discorso riportato da @francescobianco in diversi punti perché toccano la mia parte che ignora gli ostacoli. Questo discorso può portarci ad aprire una discussione proficua, almeno dal mio punto di vista. Credo che capiti anche al momento giusto visto che ci stiamo dividendo il lavoro e cominciando a costruire proprio quella struttura che vorremmo proteggesse il progetto e tutto il lavoro che ci sta dietro; trovo da questo punto di vista la scelta dei focus group molto azzeccata anche visti i numeri. Come riportava @guizzo in questa fase credo che una struttura snella ci consenta di progredire in parallelo su diversi aspetti e di costruire una base; ciò non toglie che probabilmente a andrà a ridefinire alcune delle cose fatte fino ad ora, avvicinandoci a uno di quei modelli su cui si discuteva.

**Comment by EMCestari** [comment]
Grazie innanzitutto a Francesco per il contributo importante.

Personalmente credo che un modello di governance, sebbene non sia stato deciso a tavolino, si stia pian piano andando a delineare - vedo apparire in modo piuttosto spontaneo elementi dei primi quattro modelli (forse do-ocracy un pò meno di Founder-leaded, Council-Based ed Electoral).

Il team di Governance è in fase di finalizzazione quindi non mi preoccupa molto il fatto che ad oggi “non si sia scritto su carta” a quale modello appartenere - al netto del fatto che non ho mai ritenuto opportuno copiare pari pari dei modelli ma sempre cercare di far evolvere il proprio modo di lavorare attorno a dei princìpi che possiamo decidere di sposare o meno.

Sicuramente possiamo definirci una community giovane e sicuramente, essendo umani, potremmo commettere dei passi falsi - anche questo non mi spaventa perché sono convinto che i cervelli presenti siano del tutto in grado di trarre grosso valore da eventuali errori in ottica di “lessons learned”.

Poi, come ho detto scherzosamente a Mike, sono il primo a faticare nel seguire le discussioni su Telegram - anche se comunque i sondaggi sono molto chiari e le decisioni finora sono state prese attraverso quelli. Sicuramente ci farà comodo un sistema anche più solido ma in una fase “early stage” rendere subito rigido un sistema non lo consiglierei - meglio partire snelli e veloci sapendo che abbiamo tutti la volontà di cambiare qualora si renda necessario in un secondo momento.

**Comment by akelity** [comment]
Capisco i punti ma vorrei anche io dire la mia.

Credo che ad oggi stiamo facendo (per quel poco fatto) un ottimo lavoro, non vedo ne problemi sulla governance, ne sugli strumenti di comunicazione, ne altri problemi complessi.

Siamo tanti, con tante teste diverse ed io per primo sono un forte sostenitore dell'attuale modus.

La verità è che abbiamo due strade, la prima è cercare di essere perfetti al momento zero investendo una quantità di tempo incredibile senza però iniziare a lavorare al fulcro del progetto, la seconda è partire agili, sperimentare e provare le strade, magari sbagliare, rimediare e continuare ma nel frattempo portando avanti qualcosa di tangibile sul progetto.

Personalmente se guardo alle scelte fatte non trovo grossi problemi, ma magari sono solo io che non li vedo.

Concordo però che in un progetto di questo tipo, ogni opinione vada approfondita e valutata per questo chiederei una proposta concreta su cosa cambiare e un motivo per cui sia necessario fare il cambiamento oggi.

**Comment by davideimola** [comment]
Ciao!
Grazie intanto per il messaggio, fa bene leggere ogni tanto riflessioni e spunti diversi.
Voglio però dare anche io un mio punto di vista, che si avvicina a quello di altri, tipo @akelity!

Partiamo dal presupposto che secondo il mio modesto parere come stiamo procedendo è giusto per il momento per pochi, ma semplici motivi. Stiamo iniziando nel modo più snello e agile perchè nessuno di noi può sapere cosa è effettivamente giusto o no, anche perchè community che si basano esclusivamente sullo sviluppo di un libro open source non esistono. Quindi tutto quello che stiamo facendo e provando è totalmente sperimentale e molto probabilmente sbaglieremo, ma stiamo tenendo un modello agile per permetterci di virare e sistemare in caso dovessimo evitare un iceberg! Anche perchè come dice @EMCestari non esiste un modello giusto, ma possiamo crearcene uno che vada bene nel nostro contesto!

Successivamente secondo me l'utilizzo di Telegram è utile perchè al momento è uno strumento veloce e immediato per accordarci e trovare una prima organizzazione funzionale a poter iniziare in modo positivo il libro! Perchè se dovessimo renderlo tutto open fin dalle basi risulterebbe un processo troppo lungo e forse altamente dispersivo e probabilmente più influenzabile.

Concludo dicendo che il focus non è tanto l'organizzazione, quella possiamo sempre rivederla, prima o poi, ma non possiamo concentradoci solo ed esclusivamente su trovare lo stato perfetto, perchè non esiste e perchè ci prenderebbe del tempo da quello che veramente siamo quì per fare, ovvero scrivere un libro!

Chiedo venia se qualcosa non è scritto alla perfezione, ma ho risposto prima di andare a letto e tutto di getto! Nel caso possiamo sentirci!

**Comment by elgorditosalsero** [comment]
👋🏽 

Butto giù anche la mia visione attuale.

Premessa: `odio quanto c'è troppa strutturazione, soprattutto quando non richiesta`. 

Ecco, per me, allo stato attuale, siamo esattamente in questa casistica; che è poi quello che molti altri stanno scrivendo.

Capisco bene il tuo punto @francescobianco e capisco anche che preferisci avere guidelines precise ed un ambiente molo più strutturato che altro; ma credo anche che, come già evidenziato da altri, se buttassimo tutto il focus su quello, non inizieremmo mai a lavorare perché non c'è un modello che tutti apprezzano o che condividono.

Non discuto sul fatto che in futuro servano sicuramente guidelines e modelli di governance più precisi, ma ci sarà un team dedicato apposta, quindi, direi, tempo al tempo!

Ad ogni modo, per la fase in cui siamo, credo che un processo più snello e di `learn by doing` and `learn by mistakes` è meglio, ma questo è solo il mio punto di vista 😄

**Comment by Cadienvan** [comment]
@francescobianco ti chiedo se ci sono altri punti a riguardo o se reputi che al momento la discussione ti soddisfi, molti di questi punti li rivedrai tu stesso durante il Governance Group Meeting, quindi se sei d'accordo chiuderei la issue - ovviamente non cancellandola perché i commenti sono un importante storico.

**Comment by JeyDi** [comment]
Ciao a tutti, riapro la conversazione anche a seguito dell'ultimo caso all'interno del Governance Group perchè credo sia giusto parlarne e giungere tutti assieme ad una conclusione il più velocemente possibile in modo da concentrarci su quello che secondo me è più importante in questo gruppo: scrivere un libro e dei contenuti di valore per le persone che lo leggeranno.

Capisco i dubbi che hai espresso @francescobianco , ma io non capisco concretamente cosa vuoi proporre e come le vuoi fare.

Cosa cambieresti e cosa vorresti implementare concretamente per garantire i principi che hai evidenziato?

Attualmente abbiamo:

- Un processo di selezione degli Ambassador con delle [linee guida](https://github.com/Il-Libro-Open-Source/book/blob/main/AMBASSADORS.md).
- Un gruppo telegram dove favorire le conversazioni creato a seguito di una votazione durante una call generale
- Un [codice di condotta](https://github.com/Il-Libro-Open-Source/book/blob/main/CODE_OF_CONDUCT.md) alla versione 0.1
- Una definizione dei [working group](https://github.com/Il-Libro-Open-Source/governance/blob/main/WG.md)

Cosa cambieresti e cosa adetteresti per allinearci con i principi che hai proposto?

Commento personale: vorrei evitare di cadere nella trappola della burocrazia e del dialogo infinito per questo progetto, capisco l'esigenza e la necessità di fare le cose fatte bene, ma credo che non dovremmo mai dimenticarci il nostro obiettivo che ci ha portati tutti qui. Personalmente credo che l'Open Source sia bello perchè sia aperto, ma perchè sia anche "agile" e trasparente ai cambienti. Ci saranno sempre dei problemi o delle cose che non ci vanno a genio, ma si risolvono sempre solo in un modo: contribuendo proattivamente.

Concludo citando Gauss: pauca sed matura.

**Comment by Cadienvan** [comment]
Chiudo in attesa di reali proposte visto che alcuni di questi punti sono in carico a Francesco stesso.
